# Generated by Django 2.2.6 on 2019-12-16 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='breed',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='art',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='art',
            name='age',
        ),
        migrations.AddField(
            model_name='art',
            name='created',
            field=models.TextField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='media',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
