# Generated by Django 2.2 on 2019-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191216_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.ImageField(default='DEFAULT_IMAGE_PATH', upload_to=''),
        ),
    ]
