# Generated by Django 2.2 on 2019-12-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191229_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(default='/static/images/default.png', upload_to=''),
        ),
    ]
