# Generated by Django 2.2 on 2019-12-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191229_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='image',
        ),
    ]
