# Generated by Django 2.2 on 2019-12-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_art_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.TextField(max_length=150)),
                ('show', models.CharField(choices=[('S', 'Solo'), ('D', 'Duo'), ('G', 'Group'), ('P', 'Permanent')], default='S', max_length=1)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Art')),
            ],
        ),
    ]
