# Generated by Django 2.2 on 2019-12-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date - Optional'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_date',
            field=models.DateField(verbose_name='Beginning of Exhibition'),
        ),
    ]
