# Generated by Django 2.2 on 2019-12-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20191231_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['start_date']},
        ),
    ]
