# Generated by Django 2.2 on 2019-12-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='themes',
            field=models.ManyToManyField(to='main_app.Theme'),
        ),
    ]
